### ISSUE TITLE
Check .pli file loaded

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/tugui#36]
The check on the `.pli` file loaded is performed only partially: instead of checking both its extension and its existence, only the latter is actually checked. Each of such checks is implemented into a dedicated method: the two resulting methods are associated to the same event, that is triggered when the `Entry` widget loses its focus. This results in triggering only the lastly called method.

In addition, if the `.pli` file path is entered manually, the initial and output folders are not extracted. This results in an erroneous folder where any next `.pli` selection window is opened. Think about merging the ways the entered `.pli` file is managed.

**Comment by dmanzione** [comment]
So far the `EntryVariable` class used a fixed validation procedure, implemented directly within the class itself.
In 4f12e94 it has been modified by giving the user the possibility to define the validation function to use at the instantiation of the `EntryVariable` class. The validation is now triggered each time a text is inserted in the entry widget.
The validation consists of the two required steps, first by checking the extension, second by checking the file existence. 
If the validation passes, a new event has been declared so to trigger the method for retrieving the information from the input .pli file.
Within this last method, the initial and output folders are updated accordingly, no matter the .pli file path is entered manually or not.

**Comment by dmanzione** [comment]
The bugs related to the .pli entry validation have been solved.
